apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: go-web-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/prakash-hulamani/maersk_local
  secretRef:
    name: flux-git-token

