apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go-web-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-web-app
  policy:
    semver:
      range: ">1.0.0"
