#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: go-web-app
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  path: "./k8s/manifests"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  targetNamespace: harbor

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go-web-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./k8s/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: harbor
  images:
    - name: demo.goharbor.io/harbor_flux/go-web-app  # The image to watch
      newTag: "{{ .ImageRef }}"  # Flux will update this image with the new tag
  # Optional: Set an automation strategy for image updates
  # This could be defined outside Kustomization, but it's a good example
  # of what you would configure in an ImageUpdateAutomation resource.
