apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go-web-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: "./k8s/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: go-web-app
  targetNamespace: harbor
  images:
    - name: demo.goharbor.io/harbor_flux/go-web-app
      newTag: "{{ .ImageRef }}"  # Flux will update the image tag
