apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
<<<<<<< Updated upstream
<<<<<<< Updated upstream
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkZW1vLmdvaGFyYm9yLmlvIjoge30sCiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30KICB9LAogICJjcmVkc1N0b3JlIjogIm9zeGtleWNoYWluIiwKICAiY3VycmVudENvbnRleHQiOiAicmFuY2hlci1kZXNrdG9wIgp9Cg==
=======
=======
>>>>>>> Stashed changes
type: Opaque
data:
  username: cHJha2FzaGt1c2h0YWdpCg==        # Base64 encoded value of "prakashkushtagi"
  password: SGFyYm9yQGJhbmcxCg==  # Base64 encoded value of "Harbor@bang1"
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

