apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: go-web-app
    namespace: harbor
spec:
    interval: 1m0s
    resources:
        - deployment.yaml
        - service.yaml
        - ingress.yaml
    images:
        - name: demo.goharbor.io/harbor_flux/go-web-app
          newTag: "{{ .ImageRef }}"  # Flux will update this image with new tag when available
